#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAuth.Models
{


    [System.Runtime.Serialization.DataContractAttribute()]
    public enum pcf_software_pcf_softwaretype
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Current = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Future = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Others = 3,
    }

    /// <summary>
    /// Status of the Software
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public enum pcf_software_statecode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 1,
    }

    /// <summary>
    /// Reason for the status of the Software
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public enum pcf_software_statuscode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("pcf_software")]
    public partial class Software : Microsoft.Xrm.Sdk.Entity
    {

        /// <summary>
        /// Default Constructor.
        /// </summary>
        public Software() :
                base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "pcf_software";

        public const string EntityLogicalCollectionName = "pcf_softwares";

        public const string EntitySetName = "pcf_softwares";

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }
            set
            {
                this.SetAttributeValue("ownerid", value);
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_icon")]
        public byte[] pcf_Icon
        {
            get
            {
                return this.GetAttributeValue<byte[]>("pcf_icon");
            }
            set
            {
                this.SetAttributeValue("pcf_icon", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_icon_timestamp")]
        public System.Nullable<long> pcf_Icon_Timestamp
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("pcf_icon_timestamp");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_icon_url")]
        public string pcf_Icon_URL
        {
            get
            {
                return this.GetAttributeValue<string>("pcf_icon_url");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_iconid")]
        public System.Nullable<System.Guid> pcf_IconId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("pcf_iconid");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_name")]
        public string pcf_Name
        {
            get
            {
                return this.GetAttributeValue<string>("pcf_name");
            }
            set
            {
                this.SetAttributeValue("pcf_name", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_softwarecategory")]
        public Microsoft.Xrm.Sdk.EntityReference pcf_SoftwareCategory
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pcf_softwarecategory");
            }
            set
            {
                this.SetAttributeValue("pcf_softwarecategory", value);
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_softwareid")]
        public System.Nullable<System.Guid> pcf_SoftwareId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("pcf_softwareid");
            }
            set
            {
                this.SetAttributeValue("pcf_softwareid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_softwareid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.pcf_SoftwareId = value;
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_softwaretype")]
        public virtual System.Collections.Generic.IEnumerable<pcf_software_pcf_softwaretype> pcf_SoftwareType
        {
            get
            {
                return EntityOptionSetEnum.GetMultiEnum<pcf_software_pcf_softwaretype>(this, "pcf_softwaretype");
            }
            set
            {
                this.SetAttributeValue("pcf_softwaretype", EntityOptionSetEnum.GetMultiEnum(this, "pcf_softwaretype", value));
            }
        }

        /// <summary>
        /// Status of the Software
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public virtual pcf_software_statecode? statecode
        {
            get
            {
                return ((pcf_software_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
            }
            set
            {
                this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        /// <summary>
        /// Reason for the status of the Software
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public virtual pcf_software_statuscode? statuscode
        {
            get
            {
                return ((pcf_software_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
            }
            set
            {
                this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// N:1 pcf_software_SoftwareCategory_pcf_softwarecategory
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pcf_softwarecategory")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pcf_software_SoftwareCategory_pcf_softwarecategory")]
        public MSAuth.Models.SoftwareCategory pcf_software_SoftwareCategory_pcf_softwarecategory
        {
            get
            {
                return this.GetRelatedEntity<MSAuth.Models.SoftwareCategory>("pcf_software_SoftwareCategory_pcf_softwarecategory", null);
            }
            set
            {
                this.SetRelatedEntity<MSAuth.Models.SoftwareCategory>("pcf_software_SoftwareCategory_pcf_softwarecategory", null, value);
            }
        }
    }
}
#pragma warning restore CS1591
