#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace MSAuth.Models
{


    /// <summary>
    /// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
    /// </summary>
    public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
    {

        /// <summary>
        /// Constructor.
        /// </summary>
        public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) :
                base(service)
        {
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="MSAuth.Models.Software"/> entities.
        /// </summary>
        public System.Linq.IQueryable<MSAuth.Models.Software> pcf_SoftwareSet
        {
            get
            {
                return this.CreateQuery<MSAuth.Models.Software>();
            }
        }

        /// <summary>
        /// Gets a binding to the set of all <see cref="MSAuth.Models.pcf_SoftwareCategory"/> entities.
        /// </summary>
        public System.Linq.IQueryable<MSAuth.Models.SoftwareCategory> pcf_SoftwareCategorySet
        {
            get
            {
                return this.CreateQuery<MSAuth.Models.SoftwareCategory>();
            }
        }
    }
}
#pragma warning restore CS1591
